CREATE TABLE vocab(
  ID SERIAL PRIMARY KEY,
  word VARCHAR(299) NOT NULL,
  def_en VARCHAR(299) NOT NULL,
  def_zh VARCHAR(299) NOT NULL,
  set_id INTEGER REFERENCES vocab_sets(id) ON DELETE CASCADE
);
