CREATE TABLE folders(
  ID SERIAL PRIMARY KEY,
  folder_name VARCHAR(299)
);

CREATE TABLE vocab_sets(
  ID SERIAL PRIMARY KEY,
  set_name VARCHAR(299),
  folder_id INTEGER REFERENCES folders(id) ON DELETE CASCADE
);

CREATE TABLE vocab(
  ID SERIAL PRIMARY KEY,
  word VARCHAR(299) NOT NULL,
  def_en VARCHAR(299) NOT NULL,
  def_zh VARCHAR(299) NOT NULL,
  set_id INTEGER REFERENCES vocab_sets(id) ON DELETE CASCADE
);
